### ISSUE TITLE
Double click occurring on skip forward/backward

### ISSUE THREAD

**Issue by phileday** [phileday/whirligig-old-issues#1]
https://steamcommunity.com/app/451650/discussions/0/1679190184076867745/

**Comment by phileday** [comment]
Increased doubletap time. Hopefully that should fix it.

**Comment by cheater** [comment]
what version was that pushed into?

**Comment by phileday** [comment]
I pushed a release yesterday 4.751. In truth though this isn't properly tested and was to fix the Index controllers problem.

A proper push with updates al a full list of stuff will hopefully come tomorrow.

**Comment by cheater** [comment]
Thanks, I'm testing it
