### ISSUE TITLE
cheater00_if one button or joystick already uses a function, the function can't be mapped somewhere else

### ISSUE THREAD

**Issue by phileday** [phileday/whirligig-old-issues#13]
- if one button or joystick already uses a function, the function can't be mapped somewhere else. This isn't good for two reasons: 1. you might want to have multiple buttons doing the same thing, to help ergonomics 2. let's say you have A set to Left and B set to Right. And now you want A set to Right and B set to Left. So you go to A and change it from Left, to Right. But it's still Left, because you can't have two buttons set to Right. So what you have to do is set A to some completely different function, then set B to Left, and then change A the second time, to finally set it to Right. That's confusing and a UX bug :)

**Comment by cheater** [comment]
Seems to be fixed in 4.787 or earlier. You can close this bug.
