### ISSUE TITLE
cheater00_what do the "left/right/up/down" controller options do?

### ISSUE THREAD

**Issue by phileday** [phileday/whirligig-old-issues#15]
- what do the "left/right/up/down" controller options do? It's not clear. I tried using them and left and right skip around in the movie, but that's all. Up and down don't seem to do anything.

**Comment by cheater** [comment]
bud it's been a year you need to answer this

**Comment by phileday** [comment]
> * what do the "left/right/up/down" controller options do? It's not clear. I tried using them and left and right skip around in the movie, but that's all. Up and down don't seem to do anything.

Hi

The left and right options will generally do as you say, skipping forward and backward in the movie. Regarding the up down arrows. This is more based on other menus that you can choose. So for example there are menus that have things like tilt, rotate, stretch on them. The up down arrows allow you to move the selection up and down in those menu options and then allow you to change the amounts on those values with the left and right arrows.

I hope that helps. If you have any other questions please ask and I'll try and take less that a year to answers them :)

**Comment by cheater** [comment]
ahh so that's for navigating the GUI? Thanks, that makes sense.

**Comment by cheater** [comment]
you can close the question now thank you :-)
