### ISSUE TITLE
seek bar shows up when panning up and down in cinema mode

### ISSUE THREAD

**Issue by cheater** [phileday/whirligig-old-issues#17]
This has been turned off in barrel and fish eye mode, but in cinema mode it still shows up when using the joypad to tilt the view up and down.

**Comment by phileday** [comment]
Are you sure this is still an issue? I assigned tilt to keys and did it and it seems to work my end.

**Comment by cheater** [comment]
It isn't an issue any more. This bug has been open for 9 months.. The right way to go about this would be to have change logs accompanying releases.
