### ISSUE TITLE
Back/forward slider in Playback / Advanced / Position menu inverts values

### ISSUE THREAD

**Issue by cheater** [phileday/whirligig-old-issues#44]
When you enter the menu, the slider jumps to the opposite value of what was set. So let's say your back/forward slider is set to 3.0, if you enter the menu the slider will jump to -3 and the video projection will adjust. Now the setting is actually at -3. If you exit the menu, Whirligig will keep the value -3. If you now enter the menu again, it will switch from -3 to 3.

**Comment by phileday** [comment]
Fixed in whirligig_early_access_v.4.8.

**Comment by cheater** [comment]
Confirmed
