### ISSUE TITLE
Serious bug: Playlist: drag and drop of multiple files doesn't work

### ISSUE THREAD

**Issue by cheater** [phileday/whirligig-old-issues#48]
When drag and dropping multiple files onto a playlist, only the first file gets added. All files should be added. This is a very serious bug, as drag and dropping files one by one makes it impossible to use playlists in a practical scenario, except for very small ones.

**Comment by phileday** [comment]
Now should work in whirligig_early_access_v.4.8.

**Comment by cheater** [comment]
Thanks, will test it out

**Comment by cheater** [comment]
Fixed in 4.8
