### ISSUE TITLE
Bug: no way to remove files from playlist

### ISSUE THREAD

**Issue by cheater** [phileday/whirligig-old-issues#72]
There is no way to remove files from a playlist after they have been added.

I suggest a new idea where if you press and hold A on the controller (as opposed to just tapping A), it will show a "context menu" with additional actions, like Remove. We could start with Remove, and later possibly add other things like delete file, rename file, etc.

**Comment by phileday** [comment]
There is a way to delete the file you are watching from the playlist with this trash can.

![issuer](https://user-images.githubusercontent.com/16843966/78172577-3a251000-744e-11ea-9895-c81af157f650.jpg)

**Comment by cheater** [comment]
Oh... that's right there. I think the reason I didn't see it is the
following.

The UI breaks out into two panes: "Playlists" and "Media". On the left,
Playlists has a toolbar of sorts with the "new" and "delete" buttons. So I
guess I expected it to be the same on the right. When So maybe it would
make sense to put the right trash can icon on the blue bar as well? As well
as the arrows?

**Comment by phileday** [comment]
I'll add this to the improve the Playlist UI issue and close this one.

**Comment by cheater** [comment]
It's #49 for the record
